import { z } from "zod";
export declare const EntityKindSchema: z.ZodEnum<["session", "subagent", "tool-run"]>;
export declare const NormalizedEventSchema: z.ZodObject<{
    eventId: z.ZodString;
    timestamp: z.ZodString;
    source: z.ZodString;
    sourceHost: z.ZodString;
    entityId: z.ZodString;
    sessionId: z.ZodOptional<z.ZodString>;
    parentEntityId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    entityKind: z.ZodEnum<["session", "subagent", "tool-run"]>;
    displayName: z.ZodString;
    eventType: z.ZodString;
    status: z.ZodOptional<z.ZodString>;
    summary: z.ZodOptional<z.ZodString>;
    detail: z.ZodOptional<z.ZodString>;
    activityScore: z.ZodOptional<z.ZodNumber>;
    turnId: z.ZodOptional<z.ZodString>;
    sequence: z.ZodOptional<z.ZodNumber>;
    meta: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    eventId: string;
    timestamp: string;
    source: string;
    sourceHost: string;
    entityId: string;
    entityKind: "session" | "subagent" | "tool-run";
    displayName: string;
    eventType: string;
    sessionId?: string | undefined;
    parentEntityId?: string | null | undefined;
    status?: string | undefined;
    summary?: string | undefined;
    detail?: string | undefined;
    activityScore?: number | undefined;
    turnId?: string | undefined;
    sequence?: number | undefined;
    meta?: Record<string, unknown> | undefined;
}, {
    eventId: string;
    timestamp: string;
    source: string;
    sourceHost: string;
    entityId: string;
    entityKind: "session" | "subagent" | "tool-run";
    displayName: string;
    eventType: string;
    sessionId?: string | undefined;
    parentEntityId?: string | null | undefined;
    status?: string | undefined;
    summary?: string | undefined;
    detail?: string | undefined;
    activityScore?: number | undefined;
    turnId?: string | undefined;
    sequence?: number | undefined;
    meta?: Record<string, unknown> | undefined;
}>;
export type NormalizedEvent = z.infer<typeof NormalizedEventSchema>;
export declare function parseNormalizedEvent(input: unknown): NormalizedEvent;
export declare function makeDeterministicEventId(input: {
    source: string;
    entityId: string;
    timestamp: string;
    eventType: string;
    sequence?: number;
    detail?: string;
}): string;
